In [178]:
import numpy as np
import pandas as pd

In [179]:
books = pd.read_csv("data/books.csv")
books = books.fillna("")
books

,Title,Author,Genre,SubGenre,Height,Publisher
0,Fundamentals of Wavelets,"Goswami, Jaideva",tech,signal_processing,228,Wiley
1,Data Smart,"Foreman, John",tech,data_science,235,Wiley
2,God Created the Integers,"Hawking, Stephen",tech,mathematics,197,Penguin
3,Superfreakonomics,"Dubner, Stephen",science,economics,179,HarperCollins
4,Orientalism,"Said, Edward",nonfiction,history,197,Penguin
...,...,...,...,...,...,...
206,Structure and Randomness,"Tao, Terence",science,mathematics,252,
207,Image Processing with MATLAB,"Eddins, Steve",tech,signal_processing,241,
208,Animal Farm,"Orwell, George",fiction,classic,180,
209,"Idiot, The","Dostoevsky, Fyodor",fiction,classic,197,
210,"Christmas Carol, A","Dickens, Charles",fiction,classic,196,

In [180]:
#task 2
books["TitleNunmers"] = books["Title"].str.findall("\d+").str.join("+")
books[50:76]

,Title,Author,Genre,SubGenre,Height,Publisher,TitleNunmers
50,"Brethren, The","Grisham, John",fiction,novel,174,Random House,
51,In a Free State,"Naipaul, V. S.",fiction,novel,196,Rupa,
52,Catch 22,"Heller, Joseph",fiction,classic,178,Random House,22
53,"Complete Mastermind, The",BBC,nonfiction,trivia,178,BBC,
54,Dylan on Dylan,"Dylan, Bob",nonfiction,autobiography,197,Random House,
55,Soft Computing & Intelligent Systems,"Gupta, Madan",tech,data_science,242,Elsevier,
56,Textbook of Economic Theory,"Stonier, Alfred",tech,economics,242,Pearson,
57,Econometric Analysis,"Greene, W. H.",tech,economics,242,Pearson,
58,Learning OpenCV,"Bradsky, Gary",tech,signal_processing,232,O'Reilly,
59,Data Structures Using C & C++,"Tanenbaum, Andrew",tech,computer_science,235,Prentice Hall,
60,"Computer Vision, A Modern Approach","Forsyth, David",tech,signal_processing,255,Pearson,
61,Principles of Communication Systems,"Taub, Schilling",tech,signal_processing,240,TMH,
62,Let Us C,"Kanetkar, Yashwant",tech,computer_science,213,Prentice Hall,
63,"Amulet of Samarkand, The","Stroud, Jonathan",fiction,novel,179,Random House,
64,Crime and Punishment,"Dostoevsky, Fyodor",fiction,classic,180,Penguin,
65,Angels & Demons,"Brown, Dan",fiction,novel,178,Random House,
66,"Argumentative Indian, The","Sen, Amartya",nonfiction,history,209,Picador,
67,Sea of Poppies,"Ghosh, Amitav",fiction,novel,197,Penguin,
68,"Idea of Justice, The","Sen, Amartya",philosophy,economics,212,Penguin,
69,"Raisin in the Sun, A","Hansberry, Lorraine",fiction,novel,175,Penguin,
70,All the President's Men,"Woodward, Bob",nonfiction,history,177,Random House,
71,"Prisoner of Birth, A","Archer, Jeffery",fiction,novel,176,Pan,
72,Scoop!,"Nayar, Kuldip",nonfiction,history,216,HarperCollins,
73,Ahe Manohar Tari,"Deshpande, Sunita",nonfiction,autobiography,213,Mauj,
74,"Last Mughal, The","Dalrymple, William",nonfiction,history,199,Penguin,
75,"Social Choice & Welfare, Vol 39 No. 1",Various,tech,economics,235,Springer,39+1

In [181]:
#task 3
books[books["Publisher"].str.count("[AEIOUaeiou]") < 2]

,Title,Author,Genre,SubGenre,Height,Publisher,TitleNunmers
8,Image Processing & Mathematical Morphology,"Shih, Frank",tech,signal_processing,241,CRC,
21,"Analysis, Vol I","Tao, Terence",tech,mathematics,248,HBA,
37,False Impressions,"Archer, Jeffery",fiction,novel,177,Pan,
53,"Complete Mastermind, The",BBC,nonfiction,trivia,178,BBC,
61,Principles of Communication Systems,"Taub, Schilling",tech,signal_processing,240,TMH,
...,...,...,...,...,...,...,...
206,Structure and Randomness,"Tao, Terence",science,mathematics,252,,
207,Image Processing with MATLAB,"Eddins, Steve",tech,signal_processing,241,,
208,Animal Farm,"Orwell, George",fiction,classic,180,,
209,"Idiot, The","Dostoevsky, Fyodor",fiction,classic,197,,
210,"Christmas Carol, A","Dickens, Charles",fiction,classic,196,,

In [182]:
#task 4
books[books["Author"].str.extract("(\w+)")[0].fillna("").str.match("^[^AEIOU]*[^aeiou]$")]

,Title,Author,Genre,SubGenre,Height,Publisher,TitleNunmers
1,Data Smart,"Foreman, John",tech,data_science,235,Wiley,
2,God Created the Integers,"Hawking, Stephen",tech,mathematics,197,Penguin,
3,Superfreakonomics,"Dubner, Stephen",science,economics,179,HarperCollins,
4,Orientalism,"Said, Edward",nonfiction,history,197,Penguin,
5,"Nature of Statistical Learning Theory, The","Vapnik, Vladimir",tech,data_science,230,Springer,
...,...,...,...,...,...,...,...
201,Girl with the Dragon Tattoo,"Larsson, Steig",fiction,novel,179,,
202,Girl who kicked the Hornet's Nest,"Larsson, Steig",fiction,novel,179,,
203,Girl who played with Fire,"Larsson, Steig",fiction,novel,179,,
209,"Idiot, The","Dostoevsky, Fyodor",fiction,classic,197,,
210,"Christmas Carol, A","Dickens, Charles",fiction,classic,196,,

In [183]:
#task 5
books["TitleVowels"] = books["Title"].str.count("[^AEIOUaeiou]")
books.sort_values("TitleVowels").tail(1)

,Title,Author,Genre,SubGenre,Height,Publisher,TitleNunmers,TitleVowels
115,Clash of Civilizations and Remaking of the Wor...,"Huntington, Samuel",nonfiction,history,228,Simon&Schuster,,37

In [184]:
#task 6
books[books["Title"].str.count("[A-Z][a-z]*") == 2]

,Title,Author,Genre,SubGenre,Height,Publisher,TitleNunmers,TitleVowels
0,Fundamentals of Wavelets,"Goswami, Jaideva",tech,signal_processing,228,Wiley,,16
1,Data Smart,"Foreman, John",tech,data_science,235,Wiley,,7
11,Slaughterhouse Five,"Vonnegut, Kurt",fiction,classic,198,Random House,,11
12,Birth of a Theorem,"Villani, Cedric",science,mathematics,234,Bodley Head,,12
15,"Trial, The","Kafka, Frank",fiction,classic,198,Random House,,7
...,...,...,...,...,...,...,...,...
204,Batman Handbook,,fiction,comic,270,,,10
205,Murphy's Law,,philosophy,psychology,178,,,10
206,Structure and Randomness,"Tao, Terence",science,mathematics,252,,,17
208,Animal Farm,"Orwell, George",fiction,classic,180,,,7
209,"Idiot, The","Dostoevsky, Fyodor",fiction,classic,197,,,6

In [185]:
#task 7
books[books["Author"].str.extract("(\w+)(, )(\w+)(\w+)")[2].fillna("").str.contains("[^AEIOUaeiou]{3}")]

,Title,Author,Genre,SubGenre,Height,Publisher,TitleNunmers,TitleVowels
26,"Beautiful and the Damned, The","Deb, Siddhartha",nonfiction,history,198,Penguin,,19
28,"Complete Sherlock Holmes, The - Vol I","Doyle, Arthur Conan",fiction,classic,176,Random House,,27
29,"Complete Sherlock Holmes, The - Vol II","Doyle, Arthur Conan",fiction,classic,176,Random House,,27
56,Textbook of Economic Theory,"Stonier, Alfred",tech,economics,242,Pearson,,17
59,Data Structures Using C & C++,"Tanenbaum, Andrew",tech,computer_science,235,Prentice Hall,,22
61,Principles of Communication Systems,"Taub, Schilling",tech,signal_processing,240,TMH,,24
62,Let Us C,"Kanetkar, Yashwant",tech,computer_science,213,Prentice Hall,,6
66,"Argumentative Indian, The","Sen, Amartya",nonfiction,history,209,Picador,,15
68,"Idea of Justice, The","Sen, Amartya",philosophy,economics,212,Penguin,,12
89,On Education,"Russell, Bertrand",philosophy,education,203,Routledge,,6
101,Identity & Violence,"Sen, Amartya",philosophy,philosophy,219,Penguin,,12
112,History of Western Philosophy,"Russell, Bertrand",philosophy,philosophy,213,Routledge,,21
114,Rationality & Freedom,"Sen, Amartya",science,economics,213,Springer,,13
123,Unpopular Essays,"Russell, Bertrand",philosophy,philosophy,198,,,10
172,Pointers in C,"Kanetkar, Yashwant",tech,computer_science,213,,,9
184,"Justice, Judiciary and Democracy","Ranjan, Sudhanshu",nonfiction,legal,224,,,21

In [186]:
#task 8
books["LastNameLetters"] = books["Author"].str.extract("(\w+)(, )(\w+)(\w+)")[0].str.count("\w")
books[books["LastNameLetters"] == 5]["Author"]

14          Eraly, Abraham
15            Kafka, Frank
16             Pratt, John
27           Camus, Albert
28     Doyle, Arthur Conan
29     Doyle, Arthur Conan
30             Smith, Adam
33          Capra, Fritjof
44          Capra, Fritjof
54              Dylan, Bob
55            Gupta, Madan
65              Brown, Dan
67           Ghosh, Amitav
72           Nayar, Kuldip
111            Aczel, Amir
116         Capra, Fritjof
121      Nehru, Jawaharlal
133           Singh, Simon
136           Singh, Simon
156             Mohan, Ned
166     Baz-Zohar, Michael
168           Verne, Jules
181            Sagan, Carl
189         Zaidi, Hussain
195             Brown, Dan
Name: Author, dtype: object